import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Mint from "../components/Mint";
var ether = require("../components/ethers");

var btn_val = "Connect";

var handleClick = async () => {
    ether.connect();
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Fight Club</title>
        <meta name="generictemplate" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ backgroundColor: "black" }}>
        <div
          id="head_section"
          className="w-full lg:max-w-[calc(2/3*100%)] ml-auto mr-auto flex justify-center min-h-screen-75"
          style={{ backgroundColor: "black" }}
        >
          <div className="container">
            <div className="items-center flex flex-wrap">
              <div className="w-full lg:max-w-[calc(1/5*100%)] px-4 flex-1">
                <div className="pr-12">
                  <Image
                    alt="..."
                    src="/img/logo.png"
                    className="w-full align-middle rounded-lg mt-6"
                    height="100%"
                    width="100%"
                    layout="responsive"
                    objectFit="fit"
                  />
                </div>
              </div>

              <div className="w-full lg:max-w-[calc(2/5*100%)] px-4 flex-1">
                <div className="pr-12">
                  <ul className="flex flex-col lg:flex-row list-none">
                    <li className="flex items-center">
                      <a
                        className="hover:text-black text-black px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                        href="https://discord.gg/g6KprmuE"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <img
                          alt="..."
                          src="/img/discord.svg"
                          className="align-middle rounded-lg"
                          height={35}
                          width={35}
                        />
                      </a>
                    </li>
                    <li className="flex items-center">
                      <a
                        className="hover:text-black text-black px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                        href="https://twitter.com/Fightclub_Base"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <img
                          alt="..."
                          src="/img/twitter.svg"
                          className="align-middle rounded-lg"
                          height={35}
                          width={35}
                        />
                      </a>
                    </li>
                    <li className="flex items-center">
                      <a
                        className="hover:text-black text-black px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                        href="https://opensea.io/collection/fightclubbasement"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <img
                          alt="..."
                          src="/img/opensea_black.svg"
                          className="align-middle rounded-lg"
                          height={35}
                          width={35}
                        />
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="w-full lg:max-w-[calc(2/5*100%)] flex-1">
                <div className="pr-12">
                  <button
                    className="text-white font-bold uppercase text-base px-8 py-3 rounded-full shadow-md hover:shadow-lg outline-none focus:outline-none ease-linear transition-all duration-150"
                    style={{ backgroundColor:"#d7235b",fontFamily: "montserrat" }}
                    type="button"
                    id="connetbtn"
                  onClick={() => handleClick()}
                  >
                    Connect Wallet
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          id="home"
          className="relative pt-8 flex"
          style={{ backgroundColor: "black" }}
        >
          <div className="absolute top-0 w-full h-full bg-center bg-cover">
            <span
              id="blackOverlay"
              className="w-full h-full absolute opacity-75"
            ></span>
          </div>
          <div className="container relative mx-auto">
            <div className="items-center flex flex-wrap">
              <div className="w-full lg:max-w-[calc(1/2*100%)] px-4 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <Image
                    alt="..."
                    src="/img/fightclub.png"
                    className="w-full align-middle rounded-lg mt-6"
                    height="100%"
                    width="100%"
                    layout="responsive"
                    objectFit="fit"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <Mint />
        <About />
      </main>
    </>
  );
}
