import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";
import About from "../components/About";
import JoinDiscord from "../components/JoinDiscord";
import Roadmap from "../components/Roadmap";
import Mint from "../components/Mint";
import Feature from "../components/Feature";
import Space from "../components/Space";

export default function Home() {
  return (
    <>
      <Head>
        <title>Soltars - Series of Blockchain NFT Project</title>
        <meta name="soltar" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div
          id="home"
          className="relative pt-16 pb-32 flex-none lg:flex content-center items-center justify-center min-h-screen-75"
          style={{
            backgroundColor: "white",
            backgroundImage: "url(img/banner-bg.jpg)",
            backgroundSize: "cover",
          }}
        >
          <div className="w-full lg:max-w-[calc(2/5*100%)] px-4 text-center"></div>
          <div className="w-full lg:max-w-[calc(1/5*100%)] px-4">
            <Image
              alt="..."
              src="/img/logo-banner.png"
              className="w-full align-middle rounded-lg mt-6"
              height="100%"
              width="100%"
              layout="responsive"
              objectFit="contain"
            />
          </div>
          <div className="w-full lg:max-w-[calc(2/3*100%)] px-4">
            <Image
              alt="..."
              src="/img/character-1.png"
              className="w-full align-middle rounded-lg mt-6 lg:content-start lg:items-start"
              height="100%"
              width="100%"
              layout="responsive"
              objectFit="contain"
            />
          </div>
        </div>

        <About />
        <Feature />
        <Space />
        <JoinDiscord />
        <Mint />
        <Roadmap />
      </main>
      <Footer />
    </>
  );
}
