import Head from 'next/head';
import {React, useEffect, useState} from "react";
import Navbar from '../components/NavBar';
import Footer from '../components/Footer';

var ether = require('../components/ethers');

import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';

const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 3000 },
    items: 5
  },
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 5
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 4
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1
  }
};


export default function Home() {

  const [partyTime, setPartyTime] = useState("");
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);
  const [numberofnfts,setNumberofNFT] = useState(1);
  const [ogbadgeid,setOgBadgeId] = useState();
  const [disable, setDisable] = useState(true);

  var minthandler = async () => {
    ether.mintPass(numberofnfts);
  };

  useEffect(() => {
    
    ether.listenmetamaskchange();

    const target = new Date("10/08/2021 18:00:00 UTC");
    
    const interval = setInterval(() => {
      const now = new Date();
      const difference = target.getTime() - now.getTime();

      const d = Math.floor(difference / (1000 * 60 * 60 * 24));
      setDays(d);

      const h = Math.floor(
        (difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
      );
      setHours(h);

      const m = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
      setMinutes(m);

      const s = Math.floor((difference % (1000 * 60)) / 1000);
      setSeconds(s);

      if (d <= 0 && h <= 0 && m <= 0 && s <= 0) {
        setPartyTime("We are Live Now!!")
        setDays(0);
        setHours(0);
        setMinutes(0);
        setSeconds(0);
        setDisable(false);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
        <title>Pumpkin | Hedz NFT</title>
        <meta name="pumpkin" content="Generated by create next app" />
        <link rel="icon" href="/pumpkin.ico" />
      </Head>
      <Navbar />
      <main>
        <div
          id="home"
          className="relative pt-16 pb-32 flex content-center items-center justify-center min-h-screen-75"
          style={{ backgroundColor: "#f3931f" }}
        >
          <div className="absolute top-0 w-full h-full bg-center bg-cover">
            <span
              id="blackOverlay"
              className="w-full h-full absolute opacity-75"
            ></span>
          </div>
          <div className="container relative mx-auto">
            <div className="items-center flex flex-wrap">
              <div className="w-full px-6 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <h1
                    className="leading-normal mt-0 mb-2 text-black uppercase"
                    style={{ fontFamily: "ScaryHalloween", fontSize: "4rem" }}
                  >
                    <b>Welcome to the Pumpkin Hedz NFT</b>
                    
                  </h1>
                  <p className="mt-4 font-montserrat text-lg text-blueGray-200"></p>
                </div>
              </div>

              <div className="w-full px-4 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <img
                    alt="..."
                    src="/img/logo_opt.png"
                    className="w-full align-middle rounded-lg mt-6"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>

        <section id="aboutus" className="relative py-20 bg-black">
          <div className="container mx-auto px-4 text-white">
            <div className="items-center flex flex-wrap">
              <div className="w-full md:w-4/12 ml-auto mr-auto px-4">
                <img
                  alt="..."
                  className="max-w-full rounded-lg shadow-lg"
                  src="/img/orange.png"
                />
              </div>
              <div className="w-full md:w-4/12 ml-auto mr-auto px-4">
                <div className="md:pr-12">
                  
                  <h3
                    className="text-3xl font-semibold"
                    style={{ color: "#f3931f", fontFamily: "ScaryHalloween" }}
                  >
                    About Pumpkin Hedz
                  </h3>
                  <p
                    className="mt-4 text-lg leading-relaxed text-white"
                    style={{ fontFamily: "HalloweenInline" }}
                  >
                    Pumpkin Hedz Is a Collection of 10,000 Unique NFT&apos;s on
                    the Ethereum Blockchain. Your Pumpkin Hedz NFT Will Grant
                    You Membership To The Pumpkinz and Will Gain You Complete
                    Access To Our VIP Area.
                    <br />
                    <br />
                    Each Pumpkin Hedz Will Grant You Full Creative And
                    Commercial Rights For As Long As You Own The NFT.
                    <br />
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="gallary" className="relative py-20 bg-black">
          <div className="container mx-auto px-4 text-white">
            <div className="w-full px-4 py-10 flex-1 ml-auto mr-auto">
            <Carousel
                responsive={responsive}
                autoPlay={true}
                autoPlaySpeed={1000}
                infinite={true}
                itemClass="carousel-item-padding-40-px"
                transitionDuration={1000}
                containerClass="carousel-container"
                removeArrowOnDeviceType={["tablet", "mobile"]}
              >
                <div>
                  <img
                    alt="..."
                    src="/img/2_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/3_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/8_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/9_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/10_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/11_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/12_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/13_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/14_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/15_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
                <div>
                  <img
                    alt="..."
                    src="/img/16_opt.png"
                    className="w-half align-middle rounded-lg px-3"
                  />
                </div>
              </Carousel>
            </div>
          </div>
        </section>

        <section
          id="minting"
          className="relative pb-20"
          style={{ backgroundColor: "#f3931f" }}
        >
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap"></div>

            <div className="flex flex-wrap items-center mt-32">
              <div className="w-full md:w-6/12 px-4 py-4 mr-auto ml-auto">
                
                <h3
                  className="text-3xl text-black mb-2 font-semibold leading-normal"
                  style={{ fontFamily: "ScaryHalloween" }}
                >
                  Mint Pumpkin Hedz
                </h3>
                <p
                  className="text-lg font-light leading-relaxed mt-4 mb-4 text-black"
                  style={{ fontFamily: "HalloweenInline" }}
                >
                  To Mint A Pumpkin Hedz NFT You Will Need A Mint Pass. Your
                  Mint Pass Can be Redeemed At Any Time Or Held For A Chance To
                  Win A Legendary Pumpkin Hed.
                </p>
                <img
                    alt="..."
                    src="/img/pass.gif"
                    className="w-half align-middle rounded-lg"
                  />
                
              </div>

              <div className="w-full md:w-4/12 px-4 mr-auto ml-auto">
                <div className="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-2xl rounded-lg bg-blueGray-200 border-0">
                  <div className="rounded-t mb-0 px-6 py-6">
                    <div className="text-center mb-3">
                      <h6
                        className="text-black text-xl font-bold"
                        style={{ fontFamily: "ScaryHalloween" }}
                      >
                        Public Mint
                      </h6>
                    </div>
                    <div className="btn-wrapper text-center mx-auto">
                      <div className="bg-black text-white rounded-lg">
                          <h1 className="text-3xl text-center mb-3 font-extralight text-white" style={{ fontFamily: "ScaryHalloween"}}>{partyTime}</h1>
                          <div className="text-xl text-center flex w-full items-center justify-center" style={{ fontFamily: "ScaryHalloween"}}>
                              <div className="w-24 mx-1 p-2 ">
                                  <div className="leading-relax">{days}</div>
                                  <div className="text-sm leading-relax">DD</div>
                              </div>
                              <div className="w-24 mx-1 p-2 ">
                                  <div className="leading-relax">{hours}</div>
                                  <div className="text-sm leading-relax">HH</div>
                              </div>
                              <div className="w-24 mx-1 p-2 ">
                                  <div className="leading-relax">{minutes}</div>
                                  <div className="text-sm leading-relax">MM</div>
                              </div>
                              <div className="w-24 mx-1 p-2">
                                  <div className="leading-relax" >{seconds}</div>
                                  <div className="text-sm leading-relax">SS</div>
                              </div>
                          </div>
                          </div>
                    </div>
                    <hr className="mt-6 border-b-1 border-blueGray-300" />
                  </div>
                  <div className="flex-auto px-4 lg:px-10 py-10 pt-0">
                    <div className="text-blueGray-400 text-center mb-3 font-bold"></div>
                    <form>
                      <div className="relative w-full mb-">
                        <label
                          className="block uppercase text-black text-xs font-bold mb-2"
                          style={{ fontFamily: "ScaryHalloween" }}
                        >
                          Number Of NFT to Mint
                        </label>
                        <div className="relative">
                          <input
                            type="text"
                            className="border-0 h-14 w-full pl-8 pr-20 rounded-lg z-0 focus:shadow focus:outline-none"
                            placeholder="Max 10"
                            onChange={(e) => {
                              setNumberofNFT(e.target.value);
                            }}
                            value={numberofnfts}
                            id="numberofnft"
                          />
                          <div className="absolute top-2 right-2">
                            <button
                              type="button"
                              className="h-10 w-20 text-white rounded-lg bg-black"
                              style={{ fontFamily: "ScaryHalloween" }}
                              onClick={(e) => {
                                setNumberofNFT(10);
                              }}
                            >
                              Max
                            </button>
                          </div>
                        </div>
                      </div>

                      <div className="flex w-full mb-3 mt-2">
                        <div className="w-full md:w-4/12 px-4 mr-auto ml-auto">
                          <h6
                            className="text-black text-lg"
                            id="total"
                            style={{ fontFamily: "ScaryHalloween" }}
                          >
                            Total
                          </h6>
                        </div>
                        <div className="w-full md:w-4/12 px-4 mr-auto ml-auto"></div>
                        <div className="w-full md:w-4/12 px-4 mr-auto ml-auto">
                          <h6 className="text-black text-lg" style={{ fontFamily: "ScaryHalloween" }}>
                            {numberofnfts * 0.08} ETH
                          </h6>
                        </div>
                      </div>
                      <div className="text-center mt-6">
                        <button
                          className="bg-black text-white hover:bg-blueGray-600 text-sm font-bold uppercase px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 w-full ease-linear transition-all duration-150"
                          type="button"
                          id="mint"
                          disabled={disable}
                          style={{ fontFamily: "ScaryHalloween" }}
                          onClick={() => minthandler()}
                        >
                          Mint
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="roadmap" className="pb-20 relative block bg-black">
          <div className="container mx-auto px-4 lg:pt-24 lg:pb-64">
            <img 
                alt="..." 
                src="/img/roadmap2.png" 
            />
          </div>
        </section>

        <section
          id="team"
          className="relative pt-20 pb-48"
          style={{ backgroundColor: "#f3931f" }}
        >
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap justify-center text-center mb-24">
              <div className="w-full lg:w-6/12 px-4">
                <h2 className="text-4xl text-black font-semibold" style={{ fontFamily: "ScaryHalloween"}}>Our Team</h2>
                <p className="text-lg leading-relaxed m-4 text-white"></p>
              </div>
            </div>
            <div className="flex flex-wrap">
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/blink.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-black text-xl font-bold">BLINK</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      Lead Manager
                    </p>

                    {/* <div className="mt-6">
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-twitter"></i>
                        </button>
                      </a>
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-discord"></i>
                        </button>
                      </a>
                    </div> */}
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/dusk.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-black text-xl font-bold">DUSK</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      Marketing Head
                    </p>
                    {/* <div className="mt-6">
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-twitter"></i>
                        </button>
                      </a>
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-discord"></i>
                        </button>
                      </a>
                    </div> */}
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/menza.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-black text-xl font-bold">MENZA</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      Lead Artist
                    </p>
                    {/* <div className="mt-6">
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-twitter"></i>
                        </button>
                      </a>
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-discord"></i>
                        </button>
                      </a>
                    </div> */}
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/jawad.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-black text-xl font-bold">JAWAD</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      Lead Dev
                    </p>
                    {/* <div className="mt-6">
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-twitter"></i>
                        </button>
                      </a>
                      <a
                        href="https://twitter.com/"
                        target="_blank"
                        rel="noreferrer"
                      >
                        <button
                          className="bg-black text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                          type="button"
                        >
                          <i className="fab fa-discord"></i>
                        </button>
                      </a>
                    </div> */}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
