import Head from "next/head";
import { React, useEffect, useState } from "react";
import Navbar from "../components/NavBar";
import Footer from "../components/Footer";

export default function Home() {
  const [partyTime, setPartyTime] = useState("");
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const target = new Date("10/23/2021 18:00:00 UTC");

    const interval = setInterval(() => {
      const now = new Date();
      const difference = target.getTime() - now.getTime();

      const d = Math.floor(difference / (1000 * 60 * 60 * 24));
      setDays(d);

      const h = Math.floor(
        (difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)
      );
      setHours(h);

      const m = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
      setMinutes(m);

      const s = Math.floor((difference % (1000 * 60)) / 1000);
      setSeconds(s);

      if (d <= 0 && h <= 0 && m <= 0 && s <= 0) {
        setPartyTime("Launched!!");
        setDays(0);
        setHours(0);
        setMinutes(0);
        setSeconds(0);
        setDisable(false);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Head>
        <title>Wolves Of Wall Street NFT</title>
        <meta
          name="Wolvesofwallstreet"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div
          id="home"
          className="relative pt-16 pb-32 flex content-center items-center justify-center min-h-screen-75"
          style={{ backgroundColor: "#c37ae5" }}
        >
          <div className="absolute top-0 w-full h-full bg-center bg-cover">
            <span
              id="blackOverlay"
              className="w-full h-full absolute opacity-75"
            ></span>
          </div>
          <div className="container relative mx-auto">
            <div className="items-center flex flex-wrap">
              <div className="w-full mt-8 px-4 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  {/* <img
                    alt="..."
                    src="/img/home_bg.png"
                    className="w-full align-middle rounded-lg mt-6"
                  /> */}
                  <video
                    poster="/img/home_bg.png"
                    autoplay="autoplay"
                    controls="controls"
                    loop
                  >
                    <source src="/img/video.mov" />
                  </video>
                </div>
              </div>
              <div className="w-full px-6 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <h1
                    className="leading-normal mt-8 mb-2 text-white uppercase"
                    style={{ fontFamily: "jost", fontSize: "3.2rem" }}
                  >
                    <b>Wolves of Wallstreet</b>
                  </h1>
                  <p className="mt-4 font-montserrat text-lg text-blueGray-200">
                    <div className="text-black rounded-lg">
                      <h1
                        className="text-3xl text-center mb-3 font-extralight text-black"
                        style={{ fontFamily: "josefin" }}
                      >
                        {partyTime}
                      </h1>
                      <div
                        className="text-2xl text-center flex w-full items-center justify-center"
                        style={{ fontFamily: "josefin" }}
                      >
                        <div className="w-24 mx-1 p-2 ">
                          <div className="leading-relax">{days}</div>
                          <div className="text-sm leading-relax">DD</div>
                        </div>
                        <div className="w-24 mx-1 p-2 ">
                          <div className="leading-relax">{hours}</div>
                          <div className="text-sm leading-relax">HH</div>
                        </div>
                        <div className="w-24 mx-1 p-2 ">
                          <div className="leading-relax">{minutes}</div>
                          <div className="text-sm leading-relax">MM</div>
                        </div>
                        <div className="w-24 mx-1 p-2">
                          <div className="leading-relax">{seconds}</div>
                          <div className="text-sm leading-relax">SS</div>
                        </div>
                      </div>
                      <div
                        className="text-2xl text-center flex w-full items-center justify-center"
                        style={{ fontFamily: "josefin" }}
                      >
                        <a
                          className="mt-4 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
                          href="https://wowsmint.com/"
                          target="_blank"
                          rel="noreferrer"
                        >
                          <button
                            className="bg-blue-400 text-white active:bg-blueGray-600 text-lg font-bold uppercase px-4 py-2 rounded shadow hover:shadow-lg outline-none focus:outline-none lg:mr-1 lg:mb-0 ml-3 mb-3 ease-linear transition-all duration-150"
                            type="button"
                            id="connetbtn"
                          >
                            <i className="fas fa-link"></i> Mint Now
                          </button>
                        </a>
                      </div>
                    </div>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <section
          id="aboutus"
          className="relative py-20"
          style={{ backgroundColor: "#c37ae5" }}
        >
          <div className="container mx-auto px-4 text-white">
            <div className="items-center flex flex-wrap">
              <div className="w-full md:w-4/12 ml-auto mr-auto px-4">
                <img
                  alt="..."
                  className="max-w-full rounded-lg shadow-lg"
                  src="/img/wows.gif"
                />
              </div>
              <div className="w-full md:w-4/12 ml-auto mr-auto px-4">
                <div className="md:pr-12">
                  <h3
                    className="text-3xl font-semibold text-white"
                    style={{ fontFamily: "josefin" }}
                  >
                    What Are Wolves of Wall Street?
                  </h3>
                  <p
                    className="mt-4 text-lg leading-relaxed text-black text-justify bg-blue-400 px-6 py-4 rounded-lg"
                    style={{ fontFamily: "josefin" }}
                  >
                    Wolves of wall street is one of the first NFT&apos;s to
                    incorporate one of the most infamous American Movies of all
                    time. The Wolves of Wall Street. We have created a limited
                    supply of 2500 suited wolves, which replicate some of the
                    characters involved within the movie.
                    <br />
                    <br />
                    Each Wolves of Wallstreet NFT is unique, with the collection
                    consisting of 2500 wolves with randomly generated features
                    such as hat, outfit, accessories and background.
                    <br />
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section
          id="stats"
          className="relative py-20"
          style={{ backgroundColor: "#c37ae5", fontFamily: "josefin" }}
        >
          <div className="container mx-auto px-4 text-black">
            <div className="w-full px-4 py-10 flex-1 ml-auto mr-auto">
              <div className="w-full p-6">
                <div className="lg:flex lg:-mx-2 justify-between mb-10">
                  <div className="lg:w-1/3 mb-4 lg:mb-0 px-2">
                    <div className="w-full flex items-center h-40 bg-blue-400 px-6 rounded-lg">
                      <div className="w-full">
                        <div className="flex justify-center my-4">
                          <span className="block material-icons fill-current text-white text-3xl">
                            Wolves Limit
                          </span>
                        </div>

                        <div className="flex justify-center my-4">
                          <span className="block text-2xl text-white">
                            2500
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="lg:w-1/3 mb-4 lg:mb-0 px-2">
                    <div className="w-full flex items-center h-40 bg-blue-400 px-6 rounded-lg">
                      <div className="w-full">
                        <div className="flex justify-center my-4">
                          <span className="block material-icons fill-current text-white text-3xl">
                            SOL to Mint a Wolve
                          </span>
                        </div>

                        <div className="flex justify-center my-4">
                          <span className="block text-2xl text-white">
                            0.9 SOL
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="lg:w-1/3 mb-4 lg:mb-0 px-2">
                    <div className="w-full flex items-center h-40 bg-blue-400 px-6 rounded-lg">
                      <div className="w-full">
                        <div className="flex justify-center my-4">
                          <span className="block material-icons fill-current text-white text-3xl">
                            Marketplaces
                          </span>
                        </div>

                        <div className="flex justify-center my-4">
                          <span className="block text-2xl text-white">1</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section
          id="roadmap"
          className="py-20 relative block"
          style={{ backgroundColor: "#c37ae5" }}
        >
          <div className="container mx-auto px-4 lg:pt-24 lg:pb-28">
            <div className="flex flex-wrap text-center justify-center">
              <div className="w-full lg:w-6/12 px-4">
                <h2
                  className="text-4xl font-semibold text-white"
                  style={{ fontFamily: "josefin" }}
                >
                  Roadmap
                </h2>
              </div>
            </div>
            <div
              className="flex flex-wrap mt-12 justify-center"
              style={{ fontFamily: "josefin" }}
            >
              <div className="w-full lg:w-4/12 px-4 text-center">
                <div className="container bg-blue-400 px-6 py-4 rounded-lg mt-3">
                  <div
                    className="p-3 w-12 h-12 shadow-lg rounded-full inline-flex items-center justify-center"
                    style={{ backgroundColor: "white" }}
                  >
                    <i className="font-bold"> L1</i>
                  </div>
                  <h5 className="text-xl mt-5 font-semibold text-white">
                    WOWS Minting Process
                  </h5>
                  <p className="mt-2 mb-4 text-justify text-white">
                    2,500 exclusive Wolves of Wallstreet NFTs will become
                    available to mint through the main website for a limited
                    time. Every NFT minted by the community will be put forward
                    as an entry for a big prize pool of $15,000 in (WOWS)
                    Rewards! A limited number of 200 exclusive NFTs will be put
                    aside for individuals that manage to secure a place in the
                    whitelist sale! We have also generously decided to favour
                    our whitelist entries by giving 2 NFTs for the price of 1.
                  </p>
                </div>
                <div className="container bg-blue-400 px-6 py-4 rounded-lg mt-3">
                  <div
                    className="p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center "
                    style={{ backgroundColor: "white" }}
                  >
                    <i className="font-bold"> L2</i>
                  </div>
                  <h5 className="text-xl mt-5 font-semibold text-white">
                    Marketing and Secondary Marketplaces
                  </h5>
                  <p className="mt-2 mb-4 text-justify text-white">
                    We have already undergone marketing procedures for (WOWS) by
                    initiating paid collaborations with NFT related content
                    creators and are also planning to target social media
                    influencers in the near future! The team will announce the
                    secondary marketplaces at public launch.After the mint, we
                    will also initiate multiple ways of marketing through
                    advertisements while supplementing this with influencer
                    action and community driven campaigns. The marketing will be
                    funded by the proceeds generated through the mint at public
                    launch.
                  </p>
                </div>
                <div className="container bg-blue-400 px-6 py-4 rounded-lg mt-3">
                  <div
                    className="p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center "
                    style={{ backgroundColor: "white" }}
                  >
                    <i className="font-bold"> L3</i>
                  </div>
                  <h5 className="text-xl mt-5 font-semibold text-white">
                    Hold and Earn
                  </h5>
                  <p className="mt-2 mb-4 text-justify text-white">
                    Holding one of our exclusive Wolves of Wallstreet NFTs will
                    then allow all holders to split 50% of royalties which will
                    benefit the holder by earning $SOL from their exclusive
                    NFTs. The more Wolves you own the more $SOL you earn!
                  </p>
                </div>
                <div className="container bg-blue-400 px-6 py-4 rounded-lg mt-3">
                  <div
                    className="p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center "
                    style={{ backgroundColor: "white" }}
                  >
                    <i className="font-bold">L4</i>
                  </div>
                  <h5 className="text-xl mt-5 font-semibold text-white">
                    The Investment Wolves Club
                  </h5>
                  <p className="mt-2 mb-4 text-justify text-white">
                    Holders of (WOWS) NFTs will be eligible to verify their
                    ownership and gain a lifetime access to The Investment
                    Wolves Club. This unlocks a continuously growing list of
                    benefits! <br />
                    Here are just a few: <br />
                    <li>Entry for (WOWS) giveaways</li>
                    <li>
                      Every user that mints an NFT gets entered into a raffle
                      for $15,000 worth of Giveaways{" "}
                    </li>
                    <li>
                      Daily giveaways for (WOWS), SOL, collaborative NFT’s and
                      more{" "}
                    </li>
                    <li>
                      Investment / Business Proposition Discussions With Big
                      Investors{" "}
                    </li>
                    <li> Investment Pitches </li>
                    <li>Private voice & text channels</li>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section
          id="team"
          className="relative pt-20 pb-48"
          style={{ backgroundColor: "#c37ae5", fontFamily: "josefin" }}
        >
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap justify-center text-center mb-24">
              <div className="w-full lg:w-6/12 px-4">
                <h2
                  className="text-4xl text-white font-semibold"
                  style={{ fontFamily: "josefin" }}
                >
                  Our Team
                </h2>
                <p className="text-lg leading-relaxed m-4 text-white"></p>
              </div>
            </div>
            <div className="flex flex-wrap">
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/1.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-white text-xl font-bold">Woof</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      co-founder
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/3.jpeg"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-white text-xl font-bold">Rendo</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      co-founder
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/4.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-white text-xl font-bold">Richard</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      co-founder
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/5.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-white text-xl font-bold">
                      Atomic Meta
                    </h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      Legendary Artist
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12 px-4">
                <div className="px-6">
                  <img
                    alt="..."
                    src="/img/3.png"
                    className="shadow-lg rounded-full mx-auto max-w-120-px"
                  />
                  <div className="pt-6 text-center">
                    <h5 className="text-white text-xl font-bold">Brown Bear</h5>
                    <p className="mt-1 text-sm text-black uppercase font-semibold">
                      marketing strategist
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
