import Head from "next/head";
import { React, useEffect, useState } from "react";
import NavbarOG from '../components/NavBarOG';
import Footer from "../components/Footer";

var ether = require("../components/ethers");

export default function Home() {
  var badgeminthandler = async () => {
    ether.mintBadge();
  };

  useEffect(() => {
    ether.listenmetamaskchange();
  }, []);

  return (
    <>
      <Head>
        <title>Pumpkin | Hedz NFT OG Badges</title>
        <meta name="pumpkin" content="Generated by create next app" />
        <link rel="icon" href="/pumpkin.ico" />
      </Head>
      <NavbarOG />
      <main>
        <div
          id="home"
          className="relative pt-16 pb-32 flex content-center items-center justify-center min-h-screen-75"
          style={{ backgroundColor: "#000000" }}
        >
          <div className="absolute top-0 w-full h-full bg-center bg-cover">
            <span
              id="blackOverlay"
              className="w-full h-full absolute opacity-75"
            ></span>
          </div>
          <div className="container relative mx-auto">
            <div className="items-center flex flex-wrap">
              <div className="w-full px-6 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <h1
                    className="leading-normal mt-0 mb-2  uppercase"
                    style={{
                      fontFamily: "ScaryHalloween",
                      fontSize: "4rem",
                      color: "#f3931f",
                    }}
                  >
                    <b>Pumpkin Hedz OG Badges</b>
                  </h1>
                  <p
                    className="leading-normal mt-0 mb-2 uppercase text-green-600"
                    style={{
                      fontFamily: "ScaryHalloween",
                      fontSize: "1.5rem",
                      color: "greenyellow",
                    }}
                  >
                    This badge is a NFT certifying that you were a Pumpkin Hedz
                    OG supporter. Owning this badge will provide access to the
                    Whitelist pre-sale of Pumpkin Hedz and ongoing future
                    benefits.
                  </p>
                </div>
                <button
                  type="button"
                  className="hover:text-green-600 mt-0 h-20 w-100 text-gray-800 rounded-lg "
                  style={{
                    fontFamily: "ScaryHalloween",
                    fontSize: "2rem",
                    background: "#f3931f",
                  }}
                  onClick={() => badgeminthandler()}
                >
                  Claim Badge
                </button>
              </div>

              <div className="w-full px-4 flex-1 ml-auto mr-auto">
                <div className="pr-12">
                  <img
                    alt="..."
                    src="/img/pumpkinhedzogbadge_opt.png"
                    className="w-full align-middle rounded-lg mt-6"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
